### ISSUE TITLE
Country flags inapporpriate for languages

### ISSUE THREAD

**Issue by svito3** [fosskers/aura#577]
Country flags are symbols of statehood and should not be used to mark languages in README (or anywhere else).

For example you may speak and use English but be from US or Ireland, or speak and use Russian but be from any of the countries that restored independence from USSR.

Please just use two-letter language codes instead of country flags.

If you have just copied this from other projects, they are doing it wrong as well!

**Comment by fosskers** [comment]
Thank you for your concern, but I think using country flags is the simplest way to get the message across. For instance, I'm Canadian and speak English natively, but I chose to put the UK flags for English. Why? Because that's where it comes from. Russian comes from Russia, etc. We had a similar discussion when [we added Chinese translations](https://github.com/fosskers/aura/pull/446) to Aura. In the end I decided that attempting to account for geopolitics is beyond the scope of this project. Thank you for your understanding.

The one problem that remains is Esperanto, since while it has no country it *does* have a flag, but that flag emoji hasn't yet been included in the unicode standard.
