### ISSUE TITLE
use shallow clones

### ISSUE THREAD

**Issue by adam-devel** [fosskers/aura#690]
shallow clone *-git packages  (using `--depth=1`) for faster cloning

**Comment by ratijas** [comment]
- why?
- what use-cases are?
- wouldn't it break stuff?
- what are the alternatives (other AUR wrappers) doing?

This issues needs more info.

**Comment by fosskers** [comment]
This may be a concern of `makepkg`, it's the thing that does the actual pulling of git sources. [Here's an example.](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flips-git#n14). Notice that the calling of `git clone` isn't present anywhere in the PKGBUILD - `makepkg` handles this.

Otherwise, `aura` already does do a shallow git clone for all packages to get their PKGBUILDs and patch files before building.

**Comment by adam-devel** [comment]
> * why?

faster cloning
> * what use-cases are?

having slow connection and/or limited bandwidth
> * wouldn't it break stuff?

maybe, but it's not obvious to me 
> * what are the alternatives (other AUR wrappers) doing?

i don't know and i don't think it really matter

**Comment by adam-devel** [comment]
> This may be a concern of `makepkg`, it's the thing that does the actual pulling of git sources. [Here's an example](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flips-git#n14). Notice that the calling of `git clone` isn't present anywhere in the PKGBUILD - `makepkg` handles this.
> 
> Otherwise, `aura` already does do a shallow git clone for all packages to get their PKGBUILDs and patch files before building.

i think, when a repository is already cloned, `makepkg` does not re-clone it.
maybe this can be taken advantage of to allow aura to handle this part? (cloning repositories for `makepkg`)
i think at this point this is too much for aura to handle, and might even be considered out of the scope of an aur helper

**Comment by fosskers** [comment]
It would require bash parsing, which isn't considering good practice anymore.

**Comment by fosskers** [comment]
I'm going to look into `makepkg` and see if a patch is necessary there.

**Comment by Morganamilo** [comment]
https://wiki.archlinux.org/index.php/User:Apg#makepkg:_shallow_git_clones

**Comment by micwoj92** [comment]
This was proposed and rejected (probably more than once) on pacman tracker 
https://wiki.archlinux.org/index.php/User:Apg#makepkg:_shallow_git_clones
but there is a way which I've been using couple times https://gist.github.com/andrewgregory/770cbedfa2da3817d762483155a330b8

**Comment by adam-devel** [comment]
@fosskers would it be acceptable to have a flag that would make aura wrap `makepkg` like this:
> https://gist.github.com/andrewgregory/770cbedfa2da3817d762483155a330b8

**Comment by Morganamilo** [comment]
It would break any packages that make use of checkout in the pkgbuild.

**Comment by adam-devel** [comment]
yeah, its why i asked if it would be acceptable to have it under a flag (not a default behaviour)

**Comment by ratijas** [comment]
Yesterday I was probably drunk AF or something, and I mistook the issue to be a request for NOT doing _recursive_ clones. Naturally, I felt surprised and wtf'ed about it.

I'm sorry, and I take my words (https://github.com/fosskers/aura/issues/690#issuecomment-771610305) back.

Since this is not a technical restriction of aura, but simply a matter of breaking weird PKGBUILDs at compile-time, I believe this feature would quite acceptable as an opt-in flag.

**Comment by fosskers** [comment]
@Morganamilo Thanks for the link. Well the Arch devs might not like it, but I don't see why we shouldn't. Parsing the `.SCINFO` instead would be one way to fetch all the sources ahead of time. And indeed if done so, I don't think `makepkg` tries again. I can experiment with this.

**Comment by Morganamilo** [comment]
If you choose to bypass makepkg with the source downloading then you'll have to handle #commit= #tag= ?siged and so on.

**Comment by fosskers** [comment]
We will have to explore this as a new feature after the 4.0 release.

**Comment by fosskers** [comment]
Hi guys, thanks for the original discussion. I'm close to releasing Aura 4 and am going back through old issues. I've decided not to explore this request and let `makepkg` be `makepkg`. Please let me know if you have any other issues. Cheers.
