### ISSUE TITLE
-h flag not consistent with Pacman.

### ISSUE THREAD

**Issue by dipunm** [fosskers/aura#701]
I am still a little new to arch and pacman, so I often run commands like `pacman -Rscuh` whereby I write most of my command but just want to double check the arguments.

pacman will always show the relevant help options, but when using aura, I always get the aura specific help info, it never forwards to pacman.

I propose that when using main params: `Q`, `R` and `S` (possibly others) then forward the command to pacman help.

**Comment by fosskers** [comment]
The `-h` output of the current Aura `3.x` series is one of the things I dislike most about it, but luckily this problem is already solved in the on-going [Rust port](https://github.com/fosskers/aura/discussions/657) ([see here](https://github.com/fosskers/aura/pull/671) for the associated PR). 

The new functionality allows you to be very granular with `-h` alongside the big-letter subcommands. If you're able to wait for the `4.0` release, this will be automatically fixed for you. Until then, you can also check out Aura's man page (`man aura`) or explore [the book](https://fosskers.github.io/aura/).
