### ISSUE TITLE
List all remote AUR packages

### ISSUE THREAD

**Issue by mb720** [fosskers/aura#779]
Hi and thanks a lot for aura!

Reading aura's manual, I couldn't find a way to list all remote AUR packages. I'm looking for the equivalent of

    pacman -S --list

but for packages in AUR.

The reason I'd like this is to have a minimal command line browser for AUR packages, just like

    pacman -S --list --quiet | fzf --preview 'pacman -Si {1}'

**Comment by fosskers** [comment]
Interesting suggestion, sorry for only responding now. I just moved across the world and have understandably busy.

>  I couldn't find a way to list all remote AUR packages.

Aura itself doesn't actually know the names of all available AUR packages at any given moment. This is for a few reasons:

1. Aura only stores local caches of AUR packages you've already had some contact with.
2. Full package definitions are actually available on the AUR.
3. New packages are added to the AUR all the time.

If you do want such a raw list, you could either get it from https://aur.archlinux.org/packages.gz (updated regularly) or I could *potentially* extend [faur](https://git.sr.ht/~fosskers/faur) to yield such a list as JSON as well. I'm less keen on the latter, since it would be an attack vector on the API.

Thoughts?

**Comment by mb720** [comment]
Thanks for your take on this!

By asking, I wanted to make sure that I hadn't overlooked any existing feature in Aura that would let me browse remote packages.

Reading your answer, I'd say the fastest way to browse AUR packages is using ones web browser of choice.

For a command line solution, one could whip up something in the spirit of this:

    curl https://aur.archlinux.org/packages.gz | zcat | fzf

That specific command only half works and messes up my terminal but might be used as a starting point.

**Comment by fosskers** [comment]
You're of course able to `-As` all you like too, but that'll only match on your search terms.
