### ISSUE TITLE
Check for presence of package `base-devel`

### ISSUE THREAD

**Issue by joergdw** [fosskers/aura#854]
The package `base-devel` is assumed by default to be part of `makedepends` in the PKBUILD, see [Arch Wiki](<https://wiki.archlinux.org/title/PKGBUILD#makedepends>). I propose that Aura checks this and treats this implicit make-dependency as any other that is explicitly listed in `makedepends`.

**Comment by fosskers** [comment]
Indeed. This is an easy fix and will be included in the next release.

**Comment by joergdw** [comment]
Thank you!

**Comment by aquova** [comment]
I don't think this is worth opening a separate bug report for, but I do want to point out that this can cause problems for users who prefer `doas` over `sudo` (which I believe aura supports). Upon installing `doas`, many users will uninstall `sudo` as to not have two programs with privilege escalation. `base-devel` however includes `sudo` as one of its packages, so many will install `base-devel`'s packages sans `sudo` individually, rather than the metapackage.

I don't really have a suggestion here, as I think checking for `base-devel` will be beneficial to more users than it harms, but there will be a few out there with more unorthodox systems who might run into this.

**Comment by fosskers** [comment]
Thanks for that elaboration, I hadn't considered that case.
