### ISSUE TITLE
aura 4.0 keeps wanting to rebuild git package

### ISSUE THREAD

**Issue by stef204** [fosskers/aura#876]
`aura 4.0.0 from master`

aura keeps wanting to upgrade package `i3status-git` even after just rebuilding it.  Checking `aura -Au` a second time or within minutes, `i3status-git` is selected as needed upgrade.

Note 1: I know it's tricky with git versions.....

Note 2: I am not using the `--git` option on the cli nor am I using the `git = true` in the config file.  Odd that `aura` presenting this package for rebuild?

**Comment by fosskers** [comment]
Confirmed. 
```
> aura -Au --dryrun
 i3status-git    :: 2.14.r23.ga07d3df-1 -> 2.14.r8.g28399bf-1
```
Strange when the version reported through the API is clearly the `r8` one. Checking the local clone, looking inside the `.SRCINFO` we also see `r8`. Where this is `r23` is coming from is a mystery to me at the moment.

**Comment by fosskers** [comment]
Wait no... this is the fault of the `pkgver` function and how the versions are being compared. What's _installed_ is the `r23`. It's detecting here that `r8` is somehow greater than that, because `8 > 2`, when really it should be `8 < 23`. So I need to fix something in the underlying `versions` library.
