### ISSUE TITLE
Sound Notification when sudo password is required 

### ISSUE THREAD

**Issue by elmhadji** [fosskers/aura#913]
As the title said if you could add sound notification when sudo password is required it's annoying how i leave programmes to download and install and everything work fine but when it come to the sudo password just forget it and yeah i need to do it all over (i know just the building process )

**Comment by fosskers** [comment]
> i need to do it all over

What needs to be done all over?

**Comment by elmhadji** [comment]
> > i need to do it all over
> 
> What needs to be done all over?

It's not big deal to be honest just i need to rerun the installation all over  because I've missed to put my password (some packages jut take time for building to complete that's )
**For example**  let say i want to install android-studio (with big packages ) and i got distracted or was busy with something else and forget to put my sudo password when it was need it then i have to rerun the process all over (i know that's doesn't download all over it uses  cache )  but building process take take and i literally rerun the command 5 time 😅

**Comment by fosskers** [comment]
Is it that `sudo` is timing out and the build cancels?

**Comment by elmhadji** [comment]
> Is it that `sudo` is timing out and the build cancels? If that happens you can actually reinstall via `-C` instead of `-A` since the package would have already been copied to the cache.

for real this is a great feature to now it existe , Thanks for pointing this out . and sorry for any bothering it indeed helps a lot thanks again

**Comment by ultimatespirit** [comment]
> Is it that `sudo` is timing out and the build cancels? If that happens you can actually reinstall via `-C` instead of `-A` since the package would have already been copied to the cache.

I was actually about to make an issue about this exact case, may make sense to still make one.

Anyway, while this does _work_, I hope we can agree it's not the most convenient UX. It would be really helpful if `aura -A` could detect a failure _after_ build situation and use the cache automatically, rather than the user having to know "ah yes, I can now do `aura -C <package that failed due to not the build>` and do an interactive menu to install the package", since the alternative is repeating the entire build again. At the very least having `aura -A` print a useful diagnostic like "error with pacman, consider using `aura -C <package names>` on next invocation to avoid rebuilding" would be a step up.

To give a pathological example, and this one very likely warrants an issue on its own, I ran into a case where this occurs not just from `sudo` timing out. As far as I can tell `aura` can not _replace_ `gvim` with `gvim-git`. Because `gvim` depends upon `vim-runtime` in a very lockstep manner it's required to either force install `vim-runtime` (breaking `gvim` temporarily) and then install `gvim`, or remove both before installing them. `pacman` handles this by doing... one of those two, I never bothered checking. If you did a `pacman -U vim-runtime.tar... gvim.tar...` it'll just work to replace them (whereas doing either individually would break).

For `aura`, however, I found out that it'll build one of the two (don't remember which one, presumably `vim-runtime` since it's a dependency for `gvim`), or it may have been both, and then completely break at the installation step if you had normal `gvim` and `vim-runtime` installed still. At which point... you have to know to use `aura -C`, or remove `gvim` and run `aura -A` again with the same builds repeating. For what it's worth, `aura -C gvim vim-runtime` works fine, so however it queues up installations does handle this case. It's just how `aura -A` does it that leads to breakage it seems.

N.B. I performed this vim test in late August, it's certainly possible it got fixed / was ephemeral since then. I didn't see an issue about this though, so it may be a good test case.

**Comment by fosskers** [comment]
> At the very least having aura -A print a useful diagnostic like "error with pacman, consider using aura -C <package names> on next invocation to avoid rebuilding" would be a step up.

There is potential here. I've added this idea to my list.

**Comment by fosskers** [comment]
I'm going to leave this behaviour as-is for now.
